# Generated by Django 3.2.9 on 2021-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='chucky'),
            preserve_default=False,
        ),
    ]
