# Generated by Django 3.2.9 on 2021-12-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='number',
        ),
    ]
