# Generated by Django 3.2.9 on 2021-12-02 07:28

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[user.validators.phone_validator])),
                ('code', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
