# Generated by Django 3.2.9 on 2021-12-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_phoneverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverify',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
