# Generated by Django 3.2.9 on 2021-12-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_phoneverify_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverify',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
