# Generated by Django 3.2.9 on 2021-12-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_phoneverify_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneverify',
            options={'verbose_name_plural': 'phone verifies'},
        ),
        migrations.AlterField(
            model_name='phoneverify',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
