# Generated by Django 3.2.9 on 2021-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211202_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverify',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
