# Generated by Django 3.2.9 on 2021-12-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_subscription_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='date_ends',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('F', 'free'), ('P', 'pro')], max_length=4),
        ),
    ]
