# Generated by Django 3.2.9 on 2021-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211204_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('F', 'free'), ('P', 'pro')], max_length=1),
        ),
    ]
