# Generated by Django 3.2.9 on 2021-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_subscription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('F', 'free'), ('P', 'pro')], default='F', max_length=1),
        ),
    ]
