# Generated by Django 3.2.9 on 2021-12-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_subscription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('F', 'free'), ('P', 'pro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(default='F', on_delete=django.db.models.deletion.CASCADE, to='user.subscription'),
        ),
    ]
