# Generated by Django 3.2.9 on 2021-12-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20211204_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverify',
            name='is_verified',
        ),
    ]
