# Generated by Django 3.2.9 on 2021-12-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_phoneverify_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscription'),
        ),
    ]
