# Generated by Django 3.2.9 on 2021-12-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_usersubscription_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='date_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
