# Generated by Django 3.2.9 on 2021-12-18 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20211218_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
