# Generated by Django 3.2.9 on 2021-12-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20211219_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='order_id',
            new_name='idpay_id',
        ),
    ]
