# Generated by Django 3.2.9 on 2021-12-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_rename_order_id_userorder_idpay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='idpay_id',
            field=models.CharField(max_length=100),
        ),
    ]
