# Generated by Django 3.2.9 on 2021-12-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_userorder_idpay_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='amount',
            new_name='order_id',
        ),
    ]
