# Generated by Django 3.2.9 on 2021-12-20 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_rename_amount_userorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='userorder',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userorder',
            name='track_id',
            field=models.IntegerField(),
        ),
    ]
