# Generated by Django 3.2.9 on 2021-12-20 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_doublepay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublepay',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
