# Generated by Django 3.2.9 on 2021-12-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_doublepay_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerify',
        ),
    ]
