# Generated by Django 3.2.9 on 2021-12-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_delete_phoneverify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoublePay',
        ),
    ]
